name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest pyspark==3.5.0 delta-spark==3.0.0 \
            pandas pyarrow scikit-learn joblib

      - name: Run unit tests
        run: pytest infrastructure/test/unit/ -v

      - name: Lint DAG file
        run: python -m py_compile airflow/dags/streaming_pipeline_dag.py && echo "DAG syntax OK"
